services:
  - type: web
    name: web-browser-agent-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: gunicorn app:app
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
